version: '3'
services:
  fastapi-app:
    build: ./
    container_name: fastapi-app
    ports:
      - "8000:8000"
    depends_on:
      - redis
    networks:
      - app-network

  redis:
    image: redis:latest
    container_name: app-redis
    ports:
      - "6379:6379"
    networks:
      - app-network

  locust:
    build:
      context: .
      dockerfile: Dockerfile.locust
    ports:
      - "8089:8089"
    depends_on:
      - fastapi-app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge