FROM python:3.10-slim

# Working directory
WORKDIR /app

# Copy directory contents into the container at /app
COPY . /app

# Install any needed packages specified in requirements.txt
RUN pip install -r requirements.txt
